In [1]:
import numpy as np
import pandas as pd

In [103]:
# the second name is in Mongo
la_liga_teams = [
    ('Real Madrid','Real Madrid CF'), 
    ('Atlético Madrid','Atlético de Madrid'), 
    ('Real Sociedad','Real Sociedad'), 
    ('Sevilla','Sevilla FC'), 
    ('Betis','Real Betis Balompié'), 
    ('Rayo Vallecano','Rayo Vallecano'),
    ('Barcelona','FC Barcelona'),
    ('Athletic Club','Athletic Club de Bilbao'),
    ('Espanyol','RCD Espanyol de Barcelona'),
    ('Osasuna','CA Osasuna'),
    ('Valencia','Valencia CF'),
    ('Villarreal','Villarreal CF'),
    ('Celta Vigo','RC Celta de Vigo'),
    ('Mallorca','RCD Mallorca'),
    ('Alavés','Deportivo Alavés'),
    ('Granada','Granada CF'),
    ('Elche','Elche CF'),
    ('Cádiz','Cádiz CF'),
    ('Getafe','Getafe CF'),
    ('Levante','Levante Unión Deportiva'),
]

teams = [team for _, team in la_liga_teams]

In [104]:
data = pd.read_csv('result4.csv')

In [105]:
len(data)

439632

In [106]:
data.head()

   Unnamed: 0           player                 Team    prediction
0           1       Marco John  TSG 1899 Hoffenheim  2.962129e+06
1           2  Elliot Anderson  TSG 1899 Hoffenheim  8.934312e+05
2           3   Ibrahima Cissé  TSG 1899 Hoffenheim  1.612833e+06
3           4     Idriss Saadi  TSG 1899 Hoffenheim  1.448036e+06
4           5     Pedro Brazão  TSG 1899 Hoffenheim  9.783717e+05

In [107]:
tmp = data[data.player == 'Marco John']

tmp[tmp['Team'].isin(teams)]

        Unnamed: 0      player                       Team    prediction
20448        20449  Marco John           RC Celta de Vigo  3.070990e+06
51120        51121  Marco John                 CA Osasuna  3.451924e+06
68160        68161  Marco John         Atlético de Madrid  1.296057e+07
98832        98833  Marco John              Real Sociedad  4.412511e+06
163584      163585  Marco John               RCD Mallorca  3.074717e+06
194256      194257  Marco John           Deportivo Alavés  2.962202e+06
204480      204481  Marco John                Valencia CF  4.848960e+06
211296      211297  Marco John                  Getafe CF  3.111905e+06
231744      231745  Marco John    Athletic Club de Bilbao  3.555914e+06
235152      235153  Marco John                   Cádiz CF  3.604939e+06
248784      248785  Marco John              Villarreal CF  4.710254e+06
252192      252193  Marco John  RCD Espanyol de Barcelona  4.388753e+06
259008      259009  Marco John    Levante Unión Deportiva  3.317563e+06
269232      269233  Marco John                   Elche CF  3.423056e+06
286272      286273  Marco John                 Granada CF  5.239471e+06
340800      340801  Marco John             Rayo Vallecano  2.799912e+06
344208      344209  Marco John               FC Barcelona  7.858773e+06
357840      357841  Marco John             Real Madrid CF  8.783028e+06
391920      391921  Marco John        Real Betis Balompié  4.745410e+06
415776      415777  Marco John                 Sevilla FC  8.866049e+06

In [108]:
print(len(np.unique(data.player)))

3408

In [121]:
players = []

for player_name in np.unique(data.player):

    la_liga_player = data[data.player == player_name]

    la_liga_player = la_liga_player[la_liga_player['Team'].isin(teams)]

    
    t2 = []
    
    for team_name, salary in zip(np.array(la_liga_player['Team']), np.array(la_liga_player['prediction'])):
        t = {}
        t['team_name'] = team_name
        t['prediction'] = salary
        
        t2.append(t)
        
    players.append({'name': player_name, 'predictions': t2})
    
    if (len(players) % 100) == 0: 
#         break
        print(len(players))

100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400

In [122]:
import json

with open("predictions.json", "w", encoding='utf16') as outfile:
    
    json.dump({'model':players}, outfile)